Added in small changes to hopefully allow for deploying code
Pitt-RAS/racecar pull request #13
Opened 2019-10-21 01:24 UTC by nls5260

- Improved README 
- added back in missing fake_path.yaml file

2019-10-21 23:31 UTC, asaba96 requested changes

2019-10-21 23:31 UTC, asaba96 commented on src/magellan_core/params/fake_path.yaml
> +odom_frame: odom
new line at EOF

2019-10-21 23:31 UTC, asaba96 commented on README.md
> +- Have your SSH key trusted by the NUC (see instructions in the computer-configuration folder)
@noah710 @4ndr3w is there any more details that need added?

2019-10-22 18:00 UTC, noah710 submitted a review, later dismissed

2019-10-23 19:47 UTC, asaba96 approved these changes
LGTM

2019-10-23 19:48 UTC, merged